---
- hosts: all
  become: true

  tasks:
  # first, to check the OS family of the managed nodes, print the gather facts.
    - name: To print all the ansible gather facts
      ansible.builtin.debug:
        var: ansible_facts
  # we got the OS family mentioned as 'os_family' == 'Debian' for ubuntu instances. now shutdown them
    - name: Shutdown all Ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"
